export const STRIPE_CONFIG = {
  STRIPE_PUBLISHABLE_KEY: "pk_test_51Rjnc2JItNh7Y0qBPRA25zeByOZMkB8Tlj6Mw8BP8bAI7jRguDMhFQFkU1rQZMP01C6xfDXqQVPuJbhhqfcnL53W00xpdBGOIr",
  MERCHANT_NAME: "Derma Veritas",
};
