export const tiers = [
  {
    name: "Veritas Glow",
    subtitle: "ENTRY TIER",
    price: "£80",
    billing: "Billed monthly",
    isPopular: false,
    benefits: [
      "1x ProFusion Hydrafacial monthly",
      "3x RF Microneedling area (first 3 sessions)",
      "1x PRP Hair Face (alternate months)",
      "10% off injectables & skincare",
      "Priority booking access",
    ],
    buttonText: "SELECT GLOW TIER",
    buttonColor: "bg-white",
  },
  {
    name: "Veritas Sculpt",
    subtitle: "MID TIER",
    price: "£160",
    billing: "Billed monthly",
    isPopular: true,
    benefits: [
      "3x Prolific treatments (includes top-up)",
      "1x Anti-Wrinkle Treatment (3 areas every 3 months)",
      "1x Laser Hair Removal (any area)",
      "1x RF Microneedling or PRP Facial",
      "15% off injectables & fillers",
      "Quarterly facial icons",
      "VIP event invitations",
    ],
    buttonText: "SELECT SCULPT TIER",
    buttonColor: "bg-blue-600",
  },
  {
    name: "Veritas Prestige",
    subtitle: "LUXURY TIER",
    price: "£299",
    billing: "Billed monthly",
    isPopular: false,
    benefits: [
      "Endolift (discounted annually)",
      "3x CO2 Laser sessions",
      "Quarterly Exosome therapy",
      "20% off Fillers & Anti-Wrinkle Treatment",
      "RF Microneedling included",
      "Complete hair care treatments",
      "Monthly product gifts",
      "Annual skin health report",
    ],
    buttonText: "SELECT PRESTIGE TIER",
    buttonColor: "bg-white",
  },
];
